### ISSUE TITLE
Only getting 2 FPS

### ISSUE THREAD

**Issue by Shifter2600** [mdarkness1988/Rust-Server#11]
**Describe the issue you are having**
Answer: I am using your Docker template in UNraid Performance 3 and tried RUST_SERVER_FPS 120 but the server results in only 2 FPS and in game if not moving is fine but as soon as you more it will stutter as moving.

**What was you doing before it happened**
Answer: 1st time starting the docker container.

**Screenshots**

**What are you running on (please complete the following information):**
 - OS: Unraid
 - Browser ...
 - Hardware: 64ram capped container at only 32g - 24core AMD Threadripper

**Additional information**
Add any other detail about the problem here.
I had no issues with the didstopia container and FPS.

**Comment by mdarkness1988** [comment]
Hi. Sorry for the late reply.

When you mean performance you mean the max setting option?

If so that it's a real hog in resources. 

When running the server can you tell me the ram, CPU usage it's hitting.

When you say 2 FPS is that server saying that on the rcon page or on the client end?
If client end then please tell me what the rcon FPS says.

Hope to help you with this issue and if required i will resolve this issue on an update if that is the case :)
