### ISSUE TITLE
Describe all listings

### ISSUE THREAD

**Issue by taobyebye** [mdarkness1988/Rust-Server#4]
Please describe all points in the container config e.g. for a unraid server.
There is no description how to set "(ADVANCED) Extra Startup Arguments:". 
How to set up two or more startup arguments ?
Argument1, Argument2 or +Argument1, + Argument2 ?

And 

Auto Maintenance and Auto Wipe, if the auto maintenance is set on and the auto wipe off, 
"Automatically updates server/oxide and manages wipes. " -> Nevertheless wipes if auto maintenance is on ?

Is the wipe a complete wipe, a blueprint wipe or a map wipe ?
If i want only a map wipe ?

**Comment by mdarkness1988** [comment]
Hi there. 
1. The auto maintenance basically updates oxide and server and if update is forced to wipe by rust themselves then server will wipe (normally every 3 months) .  Auto wipe let you set wipe intervals in days. 
Auto wipe wipe everything including BP. 
Will add an option so you can select what gets wiped. 

2. Advanced argument is so you can set extra settings that is listed on the rust server arguments page. Example is (maxspawn 500) etc.. 

How do you mean more then 1 argument?  You can place lots of arguments in that field like (+maxspawn 500 +minspawn 50). 

Hope these are the answers you are looking for.

**Comment by mdarkness1988** [comment]
the auto maintenance update the server and if necessary make a wipe of map and blueprints after the update. If the update don't need a wipe, it will not wipe
Auto wipe wipe independent from update
--->Now have I understood correctly?
ANSWER: Yes basically auto wipe is forced on server by yourself. 

Can you please put in a function that it update the server but do not wipe after update ?
ANSWER: You can not disable update wipe.  This happens by the rust update Dev team and if they force a wipe update there is nothing we can do about it. Normally this happens if there is new features added into the game. 

Some more question

If i want to select the map size, there are only the option of small, medium and large/massive, medium is 3500, large and massive are 6000. Can i put the size manually of 4000 ?
ANSWER: you can force your own map size via startup arguments as they take priority. 

The Part Performance,
1 = Resource Friendly (Optimized)
2 = Original (Rust Default Settings)
3 = Competitive (Resource Gobbler)
What is changed if i choose 3 ?
ANSWER: Basically sets unlimited fps server side for best tick rate,  uses more network data to keep up with it. Better AI on NPC,  more spawns on animals,  just a nicer experience in game and better for pro shooters. 

Banner URL
Can i upload and save a banner ?
ANSWER: Yes you can save a banner anywhere you like online or your own http server and place the http link in the http field. 

Announce
Is there a way to Delay each announce separate ?
ANSWER: No.  Never thought that would be needed. 

Log
Is there a way to Log all activity in a seperated file ?
ANSWER: Can you explain more on this please. 

Hope these are the answers you are looking for.

**Comment by taobyebye** [comment]
Hi,
you can force your own map size via startup arguments as they take priority.
-> what are the Arguments ? and If i put them now of 4000 after the Server is already running with medium mapsize (3500), will the Server remove all Data or only resize the map and the Data of buildings, bases, and stuff from Players will remain ?
Log -> Something that log all Activity of the Server, who was when logged in, who, has written something

**Comment by mdarkness1988** [comment]
I will look into the log system for you see if I can split commands and errors and ingame chat in separate logs for you. 
Map size will apply once the map has been deleted and recreated.

**Comment by taobyebye** [comment]
you can force your own map size via startup arguments as they take priority.
-> what are the Arguments ? 

Can you put a Blueprint wipe to the settings ? Like a wipe cyle, only for blueprints?

**Comment by mdarkness1988** [comment]
I will add the options for wipe settings under extra settings.

The command should be +server.worldsize 2000
If for some reason that don't work then try -server.worldsize 2000

Don't forget the map must be deleted so it will I'll create the new map size

**Comment by mdarkness1988** [comment]
Close due to inactive
